name: to_do
description: Simple to do list whith bloc architecture.

version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  sembast: ^1.15.1
  uuid: ^2.0.0
  path_provider: ^0.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  gate: 
    path: ./packages/gate/

flutter:
 uses-material-design: true
 assets:
 - assets/localizations/localization_en.json
 - assets/localizations/localization_ru.json
